urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    url (   r'^$',
            views.index,
            name="index"
        ),

    url (   r'^meal/new/$',
            views.NewMeal.as_view(),
            name="meal_new"
        ),

    url (   r'^meal/(?P<pk>\d+)/$',
            views.MealView.as_view(),
            name="meal_detail"
        ),

    url (   r'^meal/(?P<pk>\d+)/del/$',
            views.DeleteMeal.as_view(),
            name="meal_delete",
        ),

    url (   r'^meal/(?P<meal_id>\d+)/dish/new/$',
            views.NewDish.as_view(),
            name="add_dish"
        ),

    url (   r'^dish/(?P<pk>\d+)/del/$',
            views.DeleteDish.as_view(),
            name="dish_delete"
        ),

    url (   r'^dish/(?P<pk>\d+)/$',
            views.DishView.as_view(),
            name="dish_detail"
        ),

    url (   r'^types/$',
            views.TypesOverview.as_view(),
            name="types"
        ),

    url (   r'^types/(?P<slug>\w+)/$',
            views.TypesView.as_view(),
            name="types_detail"
        ),

    url (   r'^instances/$',
            views.StdInstListView.as_view(),
            name="std_insts"
        ),

    url (   r'^instances/(?P<pk>\d+)/$',
            views.StdInstDetailView.as_view(),
            name="std_inst_detail"
        ),

    url (   r'^inventory/$',
            views.InventView.as_view(),
            name="inventory",
            kwargs={'showAll': False}
        ),

    url (   r'^inventory/all/$',
            views.InventView.as_view(),
            name="inventory_all",
            kwargs={'showAll': True}
        ),

    url(    r'^inventory/(?P<inst_id>\d+)/$',
            views.invent_detail,
            name="inv_detail"
        ),

    url (   r'^inventory/(?P<pk>\d+)/del/$',
            views.DeleteInst.as_view(),
            name="inst_delete"
        ),

    url (   r'^standard_instance/$',
            views.getStandardInst,
            name="std_inst_raw"
        ),

    url (   r'^ticket/(?P<pk>\d+)/del/$',
            views.DeleteTicket.as_view(),
            name="inv_delete_ticket",
        ),

    url (   r'^inventory/new/$',
            views.NewInst.as_view(),
            name="inv_new"
        ),

    url (   r'^instances/new/$',
            views.NewStdInst.as_view(),
            name="std_inst_new"
        ),

    url (   r'^inventory/new_std/$',
            views.NewInstStd.as_view(),
            name="inv_new_std"
        ),

    url (   r'^about/$',
            TemplateView.as_view(template_name="mealy/about.html"),
            name="about"
        ),
]

models/meal.py
from django.db import models
from django.contrib.auth.models import User

class Meal(models.Model):
    MEAL_TYPES = (
        ("Breakfast",   "Breakfast"),
        ("Lunch",       "Lunch"),
        ("Dinner",      "Dinner"),
        ("Tea",         "Tea"),
        ("Supper",      "Supper"),
        ("Snack",       "Snack")
    )
    cons_time   = models.DateTimeField("time eaten")
    meal_type   = models.CharField(choices=MEAL_TYPES, max_length=10)
    open_cost   = models.FloatField(default=0)
    closed_cost = models.FloatField(default=0)
    meal_owner  = models.ForeignKey(User)

    def openCostsDelta(self, delta):
        self.open_cost += delta
        self.save()

    def refreshCosts(self):
        dishes = self.dish_set.all()
        self.open_cost = sum([ dish.get_open_cost() for dish in dishes ])
        self.closed_cost = sum([ dish.get_closed_cost() for dish in dishes ])
        self.save()

    def get_dish_deps(self):
        return self.dish_set.filter(ticket_deps__gt=0).count()

    def get_meal_cost(self):
        return (self.open_cost + self.closed_cost)

    def close_cost(self, dep_cost):
        #   Assume that closure will always involve shifting a positive cost
        #    from open_cost to closed_cost
        #   Then: if dep_cost < 0, this signifies a "re-opening" of costs
        self.open_cost -= dep_cost
        self.closed_cost += dep_cost
        self.save()

    def __str__(self):
        return self.meal_type + " on " + self.cons_time.strftime("%B %-d, %Y")

models/res_type.py
from django.db import models

class Resource_Type(models.Model):
    r_parent    = models.ForeignKey('self', default=None, null=True)
    r_name      = models.CharField(max_length=40)

    def __str__(self):
        return self.r_name

    class Meta:
        verbose_name    = "resource type"

models/ticket.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models import signals

from .res_inst import Resource_Inst
from .dish import Dish

class TicketManager(models.Manager):
    def create_ticket(self, resource_inst, used_on_ticket, dish,
        resource_exhausted=False):
        assert used_on_ticket > 0, "Units used must be positive"
        assert not resource_inst.exhausted, "Resource must not be exhausted"

        ticket = self.create(
            resource_inst   = resource_inst,
            used_on_ticket  = used_on_ticket,
            ticket_cost     = resource_inst.update_usage(used_on_ticket),
            par_dish        = dish
        )
        ticket.save()
        ticket.par_dish.add_dep(ticket.ticket_cost)
        if resource_exhausted:
            resource_inst.finalise()
        return ticket

class Resource_Ticket(models.Model):
    resource_inst   = models.ForeignKey(Resource_Inst)
    used_on_ticket  = models.FloatField()
    ticket_cost     = models.FloatField()
    finalised       = models.BooleanField(default=False)
    par_dish        = models.ForeignKey(Dish)

    objects = TicketManager()

    def updatePrice(self, newPrice):
        assert not self.finalised, "Ticket has been finalised"
        #   We need to find all the dishes and update the price
        delta = newPrice - self.ticket_cost
        self.ticket_cost = newPrice
        self.save()
        self.par_dish.updatePriceDelta(delta)

    def finalise(self):
        #   Do not call this method except through Resource_Inst.finalise()
        #   We need to find the meal and see if it can be finalised
        if not self.finalised:
            self.finalised = True
            self.save()
            self.par_dish.close_dep(self.ticket_cost)

    def definalise(self):
        if self.finalised:
            self.finalised = False
            self.save()
            self.par_dish.close_dep(-self.ticket_cost)

    def __str__(self):
        return self.resource_inst.res_name

    class Meta:
        verbose_name    = "resource ticket"

@receiver(signals.post_delete, sender=Resource_Ticket)
def clean_ticket(sender, **kwargs):
    ticket = kwargs.get('instance')
    was_finalised = ticket.finalised

    if was_finalised:
        ticket.resource_inst.definalise()
        ticket.par_dish.close_dep(-ticket.ticket_cost)

    ticket.par_dish.remove_ticket(ticket.ticket_cost)
    ticket.resource_inst.update_usage(-ticket.used_on_ticket)

    if was_finalised:
        ticket.resource_inst.finalise()

templates/mealy/about.html
{% extends "mealy/base.html" %}

{% block content %}
<div class="twelve columns">
  <h4>About this site</h4>
  <p>Mealy 0.5.4</p>

  <h3>Changelog</h3>
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Version</th>
        <th>Date</th>
        <th>Notes</th>
      </tr>
      <tr>
        <td>0.5.4</td>
        <td>Apr. 27, 2016</td>
        <td>User-facing:
          <ul>
            <li>Add basic features to analyse past usage</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>0.5.3</td>
        <td>Apr. 26, 2016</td>
        <td>User-facing:
          <ul>
            <li>Can create relative (variable weight) standard instances</li>
            <li>Update instance list page to reflect this</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>0.5.2</td>
        <td>Apr. 26, 2016</td>
        <td>Can add standard instances (if has permission)
        </td>
      </tr>
      <tr>
        <td>0.5.1</td>
        <td>Apr. 25, 2016</td>
        <td>User-facing:
          <ul>
            <li>Created model for units (no longer a free text field)</li>
            <li>Can now delete unused instances</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>0.5</b></td>
        <td>Apr. 24, 2016</td>
        <td>User-facing: add basic support for standard items
        </td>
      </tr>
      <tr>
        <td>0.4.5</td>
        <td>Apr. 21, 2016</td>
        <td>User-facing:
          <ul>
            <li>Add methods to delete empty meals, dishes</li>
            <li>Dish naming using highest cost item</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>0.4.4</td>
        <td>Apr. 19, 2016</td>
        <td>Non-user-facing:
          <ul>
            <li>Add hooks for filtering in django admin</li>
            <li>Fix names and plurals in django admin</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>0.4.3</td>
        <td>Apr. 10, 2016</td>
        <td>Non-user-facing:
          <ul>
            <li>More class-based views</li>
            <li>Changed custom <code>remove</code> method for tickets to a
              <code>post_delete</code> call</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>0.4.2</td>
        <td>Apr. 10, 2016</td>
        <td>Non-user-facing:
          <ul>
            <li>Employ some built-in form validation</li>
            <li>Only show resource objects to owners (!)</li>
            <li>Change some traditional views to class-based views</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td>0.4.1</td>
        <td>Apr. 9, 2016</td>
        <td>Non-user-facing:
          <ul>
            <li>Simplification of model code</li>
            <li>Deprecated some fields</li>
            <li>Added some assertions to model functions</li>
            <li>Small bugfixes in meal cost adjustment</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>0.4</b></td>
        <td>Apr. 9, 2016</td>
        <td>Add way to remove tickets
        </td>
      </tr>
      <tr>
        <td><b>0.3</b></td>
        <td>Apr. 8, 2016</td>
        <td>Added progress bars for meal closure (CSS very hackish)
        </td>
      </tr>
      <tr>
        <td>0.2.4</td>
        <td>Apr. 7, 2016</td>
        <td>Made pretty dish function safe, added "Mealy Users" group check
        </td>
      </tr>
      <tr>
        <td>0.2.3</td>
        <td>Apr. 7, 2016</td>
        <td>Switched header and navigation to a top bar
        </td>
      </tr>
      <tr>
        <td>0.2.2</td>
        <td>Apr. 6, 2016</td>
        <td>Minor enhancements.
          User-facing:
          <ul>
            <li>Added link to view all inventory items</li>
            <li>Made dish names more readable (actually show first item)</li>
            <li>Users can update an item price on its page</li>
          </ul>
          Other:
          <ul>
            <li>Modularised recalculation of tickets (inst objects)</li>
            <li>Added methods to change price, name, type of an inst</li>
        </td>
      </tr>
      <tr>
        <td>0.2.1</td>
        <td>Apr. 5, 2016</td>
        <td>Minor enhancements.
          Non-user-facing:
          <ul>
            <li>Added all inventory items for future use</li>
            <li>Added ability to arbitrarily finalise/de-finalise instances</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>0.2</b></td>
        <td>Mar. 26, 2016</td>
        <td>Significant usability enhancements.
          User-facing:
          <ul>
            <li>Changed price formatting to display £&#47;pence as sensible</li>
            <li>Show closed, open costs of meals</li>
            <li>Cleaned up meal titles</li>
            <li>Removed table of meals from main page</li>
            <li>Order dishes/tickets in meals/dishes (used to be random)</li>
            <li>Indicate open meals on calendar and add price summary</li>
            <li>Changed inventory to table layout</li>
            <li>Show more detail in inventory</li>
          </ul>
          Other:
          <ul>
            <li>Reflowed file formatting</li>
            <li>Removed extraneous templates</li>
            <li>Added filter to format prices</li>
            <li>Require user to be logged in (no AnonymousUser)</li>
          </ul>
        </td>
      </tr>
      <tr>
        <td><b>0.1</b></td>
        <td>Mar. 18, 2016</td>
        <td>Initial working release with decent styling.
          Basic functionality of adding items, meals, dishes present.</td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock content %}

templates/mealy/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="description" content="Meal Manager">
  <meta name="keywords" content="">
  <meta name="author" content="Nicholas Sim">
  <title>{% block title %}Mealy{% endblock title %}</title>
  <link href="{% static 'mealy/style.css' %}" rel="stylesheet">

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://fonts.googleapis.com/css?family=Raleway:400,300,600"
    rel="stylesheet" type="text/css">
  <link href="{% static 'skeleton/normalize.css' %}" rel="stylesheet">
  <link href="{% static 'skeleton/skeleton.css' %}" rel="stylesheet">
  <script src="{% static 'jquery/jquery-2.2.3.min.js' %}"></script>
  {% block scripts %}{% endblock %}
</head>

<body>
  <div class="container">
    <div class="row" id="navbar">
      <header>
        <div class="two columns">
          <h1>Mealy</h1>
        </div>
        <div class="eight columns">
          <nav>
            {% block links %}
            <ul>
              <li><a href="{% url 'mealy:index' %}">Main</a></li>
              <li><a href="{% url 'mealy:inventory' %}">Inventory</a></li>
            </ul>
            {% endblock links %}
          </nav>
        </div>
        <div class="two columns">
          <p><em>{{ user }}</em></p>
        </div>
      </header>
    </div>

    <div class="row">
      {% block content %}
      {% endblock content %}
    </div>

    <div class="row">
      <hr>
      <p>Mealy on <a href="https://github.com/nw0/mealy/">GitHub</a>.
        <a href="{% url 'mealy:about' %}">About this site</a></p>
    </div>
  </div>
</body>
</html>

templates/mealy/dish_detail.html
{% extends "mealy/base.html" %}
{% load mathfilters %}
{% load mealy_extras %}

{% block content %}
<div class="eight columns">
  <p>{{ object|dish_pretty }} @
    {{ object.get_closed_cost|price:object.get_open_cost}}, part of
    <a href="{% url 'mealy:meal_detail' object.par_meal.id %}">
      {{ object.par_meal }}</a></p>

  {% if object.resource_ticket_set.count %}
  <p>It has the following tickets allocated to it:</p>
  <ol>
    {% for ticket in object.resource_ticket_set.all|dictsort:"id" %}
    <li>Ticket for {{ ticket.used_on_ticket }} of
      {{ ticket.resource_inst.res_name }}
      <a href="{% url 'mealy:inv_detail' ticket.resource_inst.id %}">
        ({{ ticket.resource_inst.id }})</a> costing
        {{ ticket.ticket_cost|price }}{% if not ticket.finalised %}*{% endif %}
      </li>
    {% endfor %}
  </ol>
  {% else %}
  <p>There are no tickets associated with this meal.</p>
  <form action="{% url 'mealy:dish_delete' object.id %}" method="post">
    {% csrf_token %}
    <input type="submit" value="Delete dish"/>
  </form>
  {% endif %}
</div>
<div class="four columns">
  <h4>Add ticket</h4>
  <form action="{% url 'mealy:dish_detail' object.id %}" method="post">
    {% csrf_token %}
    {{ tkt_form.as_p }}
    <input type="submit" />
  </form>
</div>
{% endblock content %}

templates/mealy/inv_detail.html
{% extends "mealy/base.html" %}
{% load mathfilters %}
{% load mealy_extras %}

{% block content %}
<h4>{{ inst.res_name }}</h4>
<p>This is a <a href="{% url 'mealy:types_detail' inst.res_type.r_name %}">
  {{ inst.res_type.r_name }}</a>. It cost {{ inst.price|price }} for
  {{ inst.amt_original|floatformat:"-2" }} {{ inst.orig_unit }}, purchased
  on {{ inst.purchase_date|date:"M j, Y" }}. You have used
  {{ inst.used_so_far|floatformat:"-2" }} unit(s), and the
  {% if inst.best_before %}best before{% else %}<em>expiry</em>{% endif %} date
  is {{ inst.best_bef_date|date:"M j, Y" }}.</p>

<div class="row">
  <div class="four columns">
    {% if inst.exhausted %}
    <p>This instance is exhausted.</p>
    <form action="{% url 'mealy:inv_detail' inst.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="formtype" value="finalise" />
      <input type="hidden" name="finalisation" value="definal" />
      <input type="submit" value="De-finalise" />
    </form>
    {% else %}
    <p>This instance is not exhausted.</p>
    <form action="{% url 'mealy:inv_detail' inst.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="formtype" value="finalise" />
      <input type="hidden" name="finalisation" value="final" />
      <input type="submit" value="Finalise" />
    </form>
    {% endif %}

    <h4>Change attributes</h4>
    <form action="{% url 'mealy:inv_detail' inst.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="formtype" value="pricechange" />
      {{ price_form.as_p }}
      <input type="submit" />
    </form>

    <form action="{% url 'mealy:inv_detail' inst.id %}" method="post">
      {% csrf_token %}
      <input type="hidden" name="formtype" value="amtchange" />
      {{ amt_form.as_p }}
      <input type="submit" />
    </form>
  </div>

  <div class="eight columns">
    {% if tickets %}
    <h4>Ticket list</h4>
    <table>
      <thead>
        <th>Meal</th>
        <th>Dish</th>
        <th>Units</th>
        <th>Price</th>
        <th>Admin</th>
      </thead>
      <tbody>
        {% for ticket in tickets %}
        <tr>
          <td>{{ ticket.par_dish.par_meal }}</td>
          <td><a href="{% url 'mealy:dish_detail' ticket.par_dish.id %}">
            {{ ticket.par_dish }}</a></td>
          <td>{{ ticket.used_on_ticket }}</td>
          <td>{{ ticket.ticket_cost|price }}</td>
          <td><form action="{% url 'mealy:inv_delete_ticket' ticket.id %}" method="post">
            {% csrf_token %}
            <input type="submit" value="Cancel"/>
          </form></td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <h4>No tickets</h4>
    <p>This instance hasn't been used yet.</p>
    <form action="{% url 'mealy:inst_delete' inst.id %}" method="post">
      {% csrf_token %}
      <input type="submit" value="Delete Instance" />
    </form>
    {% endif %}

    <h4>Similar items</h4>
    {% if sim_list %}
    <table class="invent">
      <thead>
        <tr>
          <th>&#8470;</th>
          <th>Name</th>
          <th>Used</th>
          <th>Price</th>
          <th>Best Bef.</th>
          <th>Used?</th>
          <th>per unit</th>
        </tr>
      </thead>
      <tbody>
        {% for item in sim_list %}
        <tr>
          <td>{% if item == inst %}*{% endif %}</td>
          <td><a href="{% url 'mealy:inv_detail' item.id %}">
            {{ item.res_name }}</a> {{ item.amt_original|floatformat:"-2" }}
            {{ item.orig_unit.shortcode }}</td>
          <td>{{ item.used_so_far }}</td>
          <td>{{ item.price|price }}<br>
            {% if item.used_so_far > 0 %}
            {{ item.price|div:item.used_so_far|price }}/u
            {% else %}-{% endif %}</td>
          <td>{{ item.best_bef_date|date:"M j, Y" }}</td>
          <td>{{ item.exhausted }}</td>
          <td>{% if item.used_so_far > 0 %}
            {{ item.amt_original|div:item.used_so_far|floatformat:"-2" }}
            {{ item.orig_unit.shortcode }}/u{% else %}-{% endif %}</td>
        {% endfor %}
      </tbody>
    </table>
    <p>(*) the current instance</p>
    {% if sim_att.tot_usage > 0 %}
    <h5>Statistics</h5>
    <p>Total usage of {{ sim_att.tot_usage|floatformat:"-2" }} units for
      {{ sim_att.tot_cost|div:sim_att.tot_usage|price }} per
      {{ sim_att.tot_vol|div:sim_att.tot_usage|floatformat:"-2" }}
      {{ inst.orig_unit.shortcode }} unit.</p>

    {% if not inst.exhausted %}
    {% with m_use=inst.amt_original|mul:sim_att.tot_usage|div:sim_att.tot_vol %}
    <p>Based on past history, a {{ inst.amt_original|floatformat:"-2" }}
      {{ inst.orig_unit.shortcode }} item should last
      {{ m_use|floatformat:"-2" }} uses. Hence this instance has
      {{ m_use|sub:inst.used_so_far|floatformat:"-2" }} remaining uses, and we
      have used approximately
      {{ inst.amt_original|mul:inst.used_so_far|div:m_use|floatformat:"-2" }}
      {{ inst.orig_unit.shortcode }} of it so far.</p>
    {% endwith %}
    {% endif %}
    {% endif %}
    {% else %}
    <p>No similar items</p>
    {% endif %}
  </div>
</div>
{% endblock %}

templates/mealy/inventory.html
{% extends "mealy/base.html" %}
{% load mathfilters %}
{% load mealy_extras %}

{% block title %}Mealy - Inventory{% endblock title %}

{% block links %}
<ul>
  <li><a href="{% url 'mealy:index' %}">Main</a></li>
  <li><a href="{% url 'mealy:inventory' %}">Inventory</a></li>
  <li><a href="{% url 'mealy:types' %}">Types</a></li>
</ul>
{% endblock links %}

{% block content %}
  <div class="eight columns">
    <h4>Inventory</h4>
    {% if items %}
    {% if not showAll %}
    <p>We currently have the following items in our inventory (<a
      href="{% url 'mealy:inventory_all' %}">see all</a>):</p>
    {% else %}
    <p>This is a list of all historical items in our inventory (<a
      href="{% url 'mealy:inventory' %}">see current</a>):</p>
    {% endif %}
    <table class="u-full-width invent">
      <thead>
        <tr>
          <th>&#8470;</th>
          <th>Type</th>
          <th>Name</th>
          <th>Used</th>
          <th>Price</th>
          <th>Best Bef.</th>
        </tr>
      </thead>
      <tbody>
        {% for item in items %}
        <tr>
          <td></td>
          <td><a href="{% url 'mealy:types_detail' item.res_type.r_name %}"
            >{{ item.res_type.r_name }}</a></td>
          <td><a href="{% url 'mealy:inv_detail' item.id %}">
            {{ item.res_name }}</a> {{ item.amt_original }}
            {{ item.units_original }}</td>
          <td>{{ item.used_so_far }}</td>
          <td>{{ item.price|price }}<br>
            {% if item.used_so_far > 0 %}
            {{ item.price|div:item.used_so_far|price }}/u
            {% else %}-{% endif %}</td>
          <td>{{ item.best_bef_date|date:"M j, Y" }}</td>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <p>No items in inventory.</p>
    {% endif %}
  </div>

  <div class="four columns">
    <h4>Add items</h4>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    <form action="{% url 'mealy:inv_new' %}" method="post">
      {% csrf_token %}
      {{ niForm.as_p }}
      <input type="submit" />
    </form>
  </div>
  {% endblock content %}

templates/mealy/meals.html
{% extends "mealy/base.html" %}
{% load mathfilters %}

{% block content %}
<div class="eight columns">
  <h4>Meal list</h4>

  {% if meal_list %}
  <table class="u-full-width">
    <thead>
      <tr>
        <th>Mon</th>
        <th>Tue</th>
        <th>Wed</th>
        <th>Thu</th>
        <th>Fri</th>
        <th>Sat</th>
        <th>Sun</th>
        <th>Summary</th>
    </thead>
    <tbody>
      {% for mealwk in cal_meals %}
      <tr class="meal-cell-head">
        {% for mealday in mealwk.1 %}
        <td class="cell-head">{{ mealday.0 }}</td>
        {% endfor %}
      </tr>
      <tr class="meal-cell-foot">
        {% for mealday in mealwk.1 %}
          <td>{% for line in mealday.1 %}
            <div class="mealln">{% if line.1 %}<a href="{{line.1}}">{% endif %}
              {{ line.0 }}{% if line.2 > semi_open %}*{% endif %}
              {% if line.1 %}</a>{% endif %}{% if prog_bars %}
              <progress max="{{line.3}}" value="{{line.3|sub:line.2}}">
              </progress>{% endif %}</div><br>{% endfor %}</td>
        {% endfor %}
      </tr>
      {% endfor %}
    </tbody>
  </table>
  {% else %}
  <p>No meals.</p>
  {% endif %}
</div>

<div class="four columns">
  <h4>Add a meal</h4>
  {% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <form action="{% url 'mealy:meal_new' %}" method="post">
    {% csrf_token %}
    {{ meal_form.as_p }}
    <br />
    <input type="submit" />
  </form>
</div>
{% endblock content %}

templates/mealy/resource_type_detail.html
{% extends "mealy/base.html" %}
{% load mathfilters %}

{% block content %}
<p>This is the {{ object.r_name }} category. {% if object.r_parent %}Its parent is
  <a href="{% url 'mealy:types_detail' object.r_parent.r_name %}">{{ object.r_parent.r_name }}</a> and
  these{% else %}These{% endif %} are its children:</p>
{% if object.resource_type_set.count %}
<ul>
  {% for tp in object.resource_type_set.all %}
  <li><a href="{% url 'mealy:types_detail' tp.r_name %}">
    {{ tp.r_name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No resource types here.</p>
{% endif %}
{% endblock content %}

templates/mealy/resource_type_list.html
{% extends "mealy/base.html" %}
{% load mathfilters %}

{% block content %}
{% if object_list %}
<ul>
  {% for tp in object_list %}
  <li><a href="{% url 'mealy:types_detail' tp.r_name %}">
    {{ tp.r_name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No resource types exist.</p>
{% endif %}
{% endblock content %}

templates/mealy/standard_inst_detail.html
{% extends "mealy/base.html" %}
{% load mathfilters %}

{% block links %}
<ul>
  <li><a href="{% url 'mealy:index' %}">Main</a></li>
  <li><a href="{% url 'mealy:inventory' %}">Inventory</a></li>
  <li><a href="{% url 'mealy:std_insts' %}">Standard Items</a></li>
</ul>
{% endblock links %}

{% block content %}
<p>This is the <em>{{ object.inst_name }}</em> standard instance.</p>
{% endblock content %}

templates/mealy/types_detail.html
{% extends "mealy/base.html" %}
{% load mathfilters %}

{% block content %}
<p>This is the {{ r_type.r_name }} category. {% if r_type.r_parent %}Its parent is
  <a href="{% url 'mealy:types_detail' r_type.r_parent.r_name %}">{{ r_type.r_parent.r_name }}</a> and
  these{% else %}These{% endif %} are its children:</p>
{% if r_type.resource_type_set.count %}
<ul>
  {% for tp in r_type.resource_type_set.all %}
  <li><a href="{% url 'mealy:types_detail' tp.r_name %}">
    {{ tp.r_name }}</a></li>
  {% endfor %}
</ul>
{% else %}
<p>No resource types here.</p>
{% endif %}
{% endblock content %}